### ISSUE TITLE
F-Droid build

### ISSUE THREAD

**Issue by Mayeu** [BramBonne/privacypolice#1]
Hi,

Is it planned to also distribute the application through the f-droid repository?

Regards.

**Comment by eosrei** [comment]
+1

**Comment by wbedard** [comment]
+1

**Comment by BramBonne** [comment]
Hi all! Thanks for your interest!

I currently do not have any plans to release the app through F-Droid in parallel. However, if someone is willing to maintain it there, I will be very happy to help.

I'm not sure what the exact procedure of releasing through F-Droid is, but if only a signed APK is needed, it would be no problem for me to provide it.

Best regards
Bram

**Comment by BramBonne** [comment]
I went ahead and created a new topic for inclusion on the [F-Droid forums](https://f-droid.org/forums/topic/wi-fi-privacypolice/). Closing this issue; please re-open if you think I overlooked something.

**Comment by letkubsw** [comment]
Your app contains Google analytics. Would it be possible to create a flavor without it? Otherwise it cannot be included in F-Droid.

**Comment by BramBonne** [comment]
Thanks for your concern. The current version of PrivacyPolice does *not* contain Google Analytics. It has been stripped out completely (by commenting out all of Analytics.java, and not including the Play Services libs). Let me know if I forgot to remove something, though :-)

**Comment by letkubsw** [comment]
Oops! Thanks for clarifying.

**Comment by Mayeu** [comment]
Thank you for taking action on this :)

**Comment by Mayeu** [comment]
Just a little feedback, the app is now available on F-Droid :)

**Comment by BramBonne** [comment]
Hi Mayeu, thanks for your work!
Is there a way for me to view statistics of the PrivacyPolice listing on F-Droid? That would greatly help me substantiate the results of my research.

**Comment by Mayeu** [comment]
> Hi Mayeu, thanks for your work!
> Is there a way for me to view statistics of the PrivacyPolice listing on F-Droid? That would greatly help me substantiate the results of my research.

I didn't do anything beside finding it on F-Droid yesterday :) (I am not par of the project, just an user).

The only place I know with some package statistic is: https://gitorious.org/f-droid/fdroiddata/source/5f5fdbd5e624fc0bd2285df80e7b2ef981de1c70:stats

**Comment by BramBonne** [comment]
Oh, in that case: thanks for finding the statistics! Just what I was looking for :-)
