### ISSUE TITLE
Preferred networks are remembered even after they are removed from the PNL

### ISSUE THREAD

**Issue by BramBonne** [BramBonne/privacypolice#13]
As per mail from Denilson Sá:

> * There is a free WiFi called "X". This is the Wi-Fi that I've saved and that I want to connect.
> * There is also "Y", which is provided by a phone operator here. I don't want to connect to it. But I admit that someday in the past I had connected to it.
> * I've already selected "forget" at the Android settings, I've also cleared known hot spots (for that Wi-Fi name) in your app; still I get the question "Are you sure network 'Y' should be available right now?"

**Comment by BramBonne** [comment]
So I just looked into this bug a bit more. Could someone encountering this provide me with a bit more information as to when exactly it is occurring? I can't seem to reproduce it myself.

Also, looking at [1], it would seem very strange that a notification would be shown for a network that is not in the list of configured networks for the user, as that function is normally only triggered when checking a specific network [2] (which, as per [1] only happens for networks in the network list).

[1] https://github.com/BramBonne/privacypolice/blob/master/privacypolice/src/main/java/be/uhasselt/privacypolice/ScanResultsChecker.java#L121
[2] https://github.com/BramBonne/privacypolice/blob/master/privacypolice/src/main/java/be/uhasselt/privacypolice/ScanResultsChecker.java#L205

**Comment by BramBonne** [comment]
Marking this as 'help wanted' since we need someone to reproduce this.

**Comment by wbedard** [comment]
I was also unable to reproduce this bug.  The equipment and steps I took were as follows:
Equipment - Android (4.4.2) tablet (wifi only), Android (4.4.4) phone (wifi+LTE), home WiFi access point.
Step 1 - On tablet, forget home access point in WiFi settings
Step 2 - On tablet, turn off WiFi
Step 3 - On tablet, open WiFi Privacy Police and clear MAC address for my home access point.
Step 4 - On phone, setup WiFi hotspot (802.11g, WPA2 w/ password)
Step 5 - On tablet, turn on WiFi
Step 6 - On tablet, connect to WiFi hotspot.  WiFi Privacy Police prompts if I want hotspot's SSID available...select "Yes".

**Comment by denilsonsa** [comment]
Sadly, I won't be able to help you with this, as the screen of my phone cracked and now it has become an expensive paperweight. :disappointed:

**Comment by BramBonne** [comment]
I'll mark this as 'invalid' for now then. Feel free to re-open this bug (anyone) if you are able to reproduce it.

**Comment by denilsonsa** [comment]
I was wondering if this bug could be caused by multiple Wi-Fi names being handled by the same router (i.e., maybe the same MAC address for multiple names).
