### ISSUE TITLE
Provide an alternative strategy for allowing networks

### ISSUE THREAD

**Issue by Fiouz** [BramBonne/privacypolice#14]
Similar to issue 13, I have access to a large numbers of AP (15000 through the city) and it is a pain to explicitly manually allow them one by one. Since they are secured using EAP-SIM, is it possible to select a different access granting policy than the default MAC-based one?

**Comment by Fiouz** [comment]
Sorry I misclick on submit. I also have another use case where I have access to a smaller numbers of AP (~100) but it is also a pain to manually allow them. That network is not using EAP-SIM but PEAP.

So, to address those use cases, can we select different granting strategies on a network basis, when specific conditions are met (eg. network is configured with EAP-SIM and AP is asking for EAP / network is configured with PEAP and AP is asking for EAP)

**Comment by alanthehat** [comment]
Does this preclude or hinder the use of 'free' hotspots? I'm thinking Fon, BT-Fon, 'the Cloud' etc.

**Comment by BramBonne** [comment]
This patch does not affect open hotspots like that in any way.
