### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by KOLANICH** [BramBonne/privacypolice#15]
Hello. I have tried your app, but I still see probe requests in monitor mode. You need to change wpa_supplicant settings, to do it you need to modify a component which is used to connect to hotspots which creates settings file and starts wpa_supplicant. This probably can be done using xposed. Also could you add mac addr randomisation and displaying into it?

**Comment by BramBonne** [comment]
Hi KOLANICH.

Thanks for your concern. Ideally, yes, we would change wpa_supplicant settings. They even have this nice option called 'scan_ssid' which, when set to 0 effectively only uses broadcast probe requests instead of directed probe requests. The problem with this solution is that it won't work for non-rooted users, which is why we chose not to implement it.

That you are still seeing probe requests is normal, as we do not interfere with the actual association mechanism in Android. However, you should not see *directed* probe requests for networks that are currently not in range, and that are not cloaked networks. If this is the case, could you give me a specific example?

Thanks,
Bram

**Comment by wbedard** [comment]
Hey Bram,

Thanks for the insight into the design of Privacy Police.  In the future, do you have the time/interest in expanding the application to provide add'l functionality/privacy for rooted users?  This paradigm is seen quite often in Android file managers where rooted users would have the additional ability to view/modify protected areas of the filesystem.  What are your thoughts?

**Comment by BramBonne** [comment]
Hi wbedard,

I'm not currently planning on providing this functionality for rooted users, for a few reasons:

* My research suggests that newer Android versions do not suffer from this problem (as they are using the correct flags in wpa_supplicant). I assume that rooted users have a high chance of being on the latest Android version.
* Rooted users have the ability to set the wpa_supplicant preferences easily in any case.

However, I encourage anyone who wants to implement this functionality to submit a patch. I'll look at it, and if it doesn't break anything for non-rooted users, I'll consider merging it.

Kind regards,
Bram

**Comment by KOLANICH** [comment]
> I assume that rooted users have a high chance of being on the latest Android version.
This is wrong. I (and not only I) won't switch to 5 untill xprivacy won't work without bugs with them (allowing to leak device's ids such as imei).

AlAnd one more detail,  I see directed probe requests (the ones with ssid). My phone is n7100, omnirom 4.4.4.

**Comment by BramBonne** [comment]
Thanks for your feedback. Are the directed probe requests for networks that are currently not in range, and that are not hidden? In this case, could you open a different issue with specific information to help other people look into this?

As for MAC addr randomization, there is a great tool made by Chainfire that allows rooted users to do this. It's available at https://play.google.com/store/apps/details?id=eu.chainfire.pryfi&hl=en

For editing your wpa_supplicant configuration directly, you could try an app like https://play.google.com/store/apps/details?id=com.kmlen.WiFiConfig, or you could edit the file directly using a text editor.

**Comment by KOLANICH** [comment]
1 pryfy is working shitty. It writes new mac into file. It musn't. It must just change it.
2 I always done it manually, but the settings are constantly restored. 
3 the networks are not hidden and not in range.
