### ISSUE TITLE
Mobile device MAC address broadcast

### ISSUE THREAD

**Issue by carl091** [BramBonne/privacypolice#2]
Do you know in which situations an Android's MAC address is broadcast? For example if I had Wi-Fi enabled but no networks saved, would my device potentially produce a signal with a unique identifier such as a hardware MAC address? Is it possible to use Wi-Fi in a listening mode that allows for use of location services but otherwise undetectable by sensors in my physical vicinity?

I was not able to find the answer to this in the documentation or reddit threads.

**Comment by BramBonne** [comment]
Hi Carl!

I haven't tested the behavior of an Android smartphone that has Wi-Fi enabled, but doesn't have any networks in its list, though I would expect it to exhibit the exact same behavior as an Android phone with all of its networks disabled (which I have studied). In this case, the smartphone (or tablet) will still send 'broadcast probe requests', which do not include a network name (SSID), but which *do* include the device's hardware (MAC) address.

This means that, even if you have no networks in your list, enabling Wi-Fi on your Android device will cause it to broadcast its MAC address. I assume that this will also be the case if you disable Wi-Fi, but enable Android to 'use Wi-Fi for improving your location, even when wireless is turned off'.

As I said: I'm not entirely sure, but this is the behavior that I would expect from my previous experiences.

Hope this answers your question.

Bram

**Comment by carl091** [comment]
Thanks for the feedback. Is MAC address spoofing a feature you would/could consider in a future version?

**Comment by BramBonne** [comment]
Unfortunately, MAC address switching is not possible on Android without root access. If you do have root, however, there are some projects that try to do this. A good example is [Pry-Fi](https://play.google.com/store/apps/details?id=eu.chainfire.pryfi&hl=en) by Chainfire.
