### ISSUE TITLE
Show persistent icon in notification bar

### ISSUE THREAD

**Issue by SecUpwN** [BramBonne/privacypolice#20]
Hey @BramBonne, lovely app you've created here! Please make it show it's neat Icon so that I know it runs? I have also added it to my own Android app WIKI  on page [recommendations](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Recommendations). Continue hacking!:+1:

**Comment by BramBonne** [comment]
Hi there,

Thanks for adding me to your list! Not using a persistent icon is a design choice, as the app would then always be in memory. Instead, WiFi PrivacyPolice is only triggered by the Android OS itself when a network event occurs. This has the benefit of saving both memory and CPU cycles.

Please reopen this issue if you have reason to believe that I am wrong about this :-)

Best regards,
Bram
