### ISSUE TITLE
Data protection activation makes some connection instable

### ISSUE THREAD

**Issue by sevan6** [BramBonne/privacypolice#23]
With F-droid biild 2.1.1 I observe a new issue.
On one hotspot protected by wpa psk, the connection is instable : i see a succession of connection/deconnection which either never ends or finally succeeds after a couple of minutes.

I do not observe the issue on a WPA2 protected network, nor when the data protection option is turned off.

I tried to clear the list and even the cache and data of the app but it did not solve the issue.

**Comment by BramBonne** [comment]
This should be fixed in commit 29cc123c8a857f0d3875c604ac3e82daa3c10b32. Please re-open this issue if the fix didn't work for you.
