### ISSUE TITLE
[BUG] Doesn't add networks after clicking no button in AskPermissionActivity

### ISSUE THREAD

**Issue by 7ShaYaN7** [BramBonne/privacypolice#28]
This is my first issue reported in this repository. Good idea!

So the point, after clicking on the notification, AskPermissionActivity is called but after clicking on the "no" button nothing happens and the hotspot doesn't add to the list as a blocked network. tested on Galaxy E5 - Lollipop v5.1.1.

Happy Coding!

**Comment by BramBonne** [comment]
Thanks for reporting, I'll look into this!

**Comment by BramBonne** [comment]
The logs seem to indicate that it's working on my end:
```
12-08 10:34:54.637 27542-27542/be.uhasselt.privacypolice D/PrivacyPolice: Asking permission for EDM-Secured (24:a4:3c:13:43:81)
12-08 10:34:55.703 27542-27542/be.uhasselt.privacypolice V/PrivacyPolice: Current preferences are: {onlyConnectToKnownAccessPoints=true, enableOnlyAvailableNetworks=true}
12-08 10:34:55.704 27542-27542/be.uhasselt.privacypolice D/PrivacyPolice: Permission change: EDM-Secured 24:a4:3c:13:43:81 false
12-08 10:34:55.704 27542-27542/be.uhasselt.privacypolice I/PrivacyPolice: Adding blocked BSSID 24:a4:3c:13:43:81 for network EDM-Secured
```

Could you give me a specific example (if possible, including a logcat) that exhibits the unwanted behavior? My steps were as follows:

1. Enable 'data protection' in the app.
2. Wait for the notification asking me to add the network.
3. Click the notification, get sent to the AskPermissionActivity.
4. Click "No"

**Comment by 7ShaYaN7** [comment]
Oh, I should say this:
In fact the network has been added, but the UI should update in order to display the just added network. If do a back and return to the list, you see the network list up to date.
