### ISSUE TITLE
[Question] Behavior when leaving a trusted network WiFi

### ISSUE THREAD

**Issue by M2ck** [BramBonne/privacypolice#29]
Currently when I leave my home and so a trusted hotspot, WiFi stays enabled this is the correct behavior? 
WiFi should be disabled automatically IMO.

I'm on Samsung Galaxy S2, running on CyanogenMod 12.1.

**Comment by BramBonne** [comment]
WiFi should indeed stay enabled all the time. Wi-Fi PrivacyPolice only disables *networks* individually when they are not available, not the Wi-Fi chip as a whole.

Could you explain why you think Wi-Fi PrivacyPolice should disable Wi-Fi connectivity altogether?

**Comment by M2ck** [comment]
Thanks for explanation.

Well for avoid useless WiFi network searching and so preserve battery life. Please consider this feature at least via an option if you don't want implement it default.

**Comment by benedetto** [comment]
@M2ck There's an app called "smarter WiFi manager" that does what you ask for. It basically does a rough localization based on the phone network cells it can seen when you enable your WiFi and then activates or deactivates your WiFi based on those localizations. Works quite well most of the time.

**Comment by M2ck** [comment]
@benedetto interesting app thanks. Too bad F-Droid version seems outdated.

@BramBonne in fact maybe my suggestion is out of scope of this app?
sorry for off topic in this case.

**Comment by BramBonne** [comment]
As @benedetto already mentioned, there are other apps that allow you to do exactly that. Wi-Fi PrivacyPolice needs your Wi-Fi chip to be turned on in order to see exactly which Wi-Fi networks are available, and which should be enabled.
