### ISSUE TITLE
Add MAC address spoofing

### ISSUE THREAD

**Issue by haarp** [BramBonne/privacypolice#4]
Hey,

this seems to be pretty neat. There is however still one big factor that destroys privacy, and that's the device's MAC address being sent out during probe requests. I don't think this app takes care of that too, does it?

If it doesn't, that's something that should really be added. Afaik Apple does randomize the source MAC for each probe request, which is the right way to do it.

Could this be added?

**Comment by BramBonne** [comment]
Hi haarp,

I do appreciate your concern: your smartphone broadcasting its MAC address will allow it to be tracked by third parties, which is certainly a privacy issue. Unfortunately, changing the MAC address is not possible unless your phone is rooted, in which case options like [Pry-Fi](https://play.google.com/store/apps/details?id=eu.chainfire.pryfi&hl=en) are available.
