### ISSUE TITLE
the app is not working property on cm13

### ISSUE THREAD

**Issue by caioau** [BramBonne/privacypolice#42]
Hi I loved the app, 

but it is not working property on cyanogenmod 13.

When I connect to a wifi station, it works fine for 2 minutes e suddenly disconnects and never reconnects again.

any sugestions?

Thanks

**Comment by ka223** [comment]
On my cm13 device, when data privacy is activated, wifi connects and immediately disconnects with wifi-connectionerror. :(

**Comment by jomo** [comment]
There's some information about complications in #30, perhaps it helps you?

**Comment by ka223** [comment]
I need to grant location access?
The GPS is every time on, if I allow switching to wifi location, google play services can collect location data. This is not a good option right now.

**Comment by BramBonne** [comment]
Unfortunately, as per #30 , this is the only viable option in Android M and up. I do appreciate your concern.

I'll mark this bug as a duplicate of #30.
