### ISSUE TITLE
No wifi connection working, empty Known hotspots list

### ISSUE THREAD

**Issue by adrian-vlad** [BramBonne/privacypolice#46]
I tried the latest Wi-Fi Privacy Police (2.2.4) downloaded from Google Play and it doesn't allow any wifi connection to be made.

With both the options disabled (Privacy protection and Data protection) there is no issue and the wifi works as expected. If any of the options is enabled then the wifi connection will be closed. Viewing the connection list, all the hotspots that I have saved and can be accessed have this text written under them: "WiFi Connection Failure".

Also, if Data protection is enabled, pressing Known hotspots shows an empty page. Any attempt to connect to a new hotspot does not trigger a dialog window telling me to trust or not the hotspot.

My phone is a Motorola Moto X Force, Android 6.0

**Comment by r-a-y** [comment]
I ran into similar trouble recently with the "Wifi Connection Failure" notice.

Since you're on Marshmallow, you need to turn on Location in Android's Settings panel.

**Comment by BramBonne** [comment]
Thanks, @r-a-y, for providing Adrian with an answer! Closing this issue, let me know if the problem persists.

**Comment by anthologist** [comment]
I have quite the same issue and can't solve, I never managed to make the app working. 
The Known hotspots has always been empty, the message warning me about geolocation stays always there and I don't understand when the app is actually working, no indicator. Do I need to actually get geolocated by a GPS or is it just a allow/disallow thing? I already allowed it on permissions and enabled geolocation.
I'm on Nexus 5X, Android 7.1.2 .

**Comment by anthologist** [comment]
@BramBonne I'm on Android 8.0 now, the problem disappeared.
