### ISSUE TITLE
Xposed mac spoof

### ISSUE THREAD

**Issue by TameOfGroans** [BramBonne/privacypolice#5]
what would be needed to spoof wifi mac address?

**Comment by BramBonne** [comment]
You would need root, and an app like Chainfire's [Pry-Fi](https://play.google.com/store/apps/details?id=eu.chainfire.pryfi&hl=en) to change your MAC automatically, or a shell or one of [these apps](https://play.google.com/store/search?q=mac%20address%20changer&c=apps&hl=en) to change it manually.

**Comment by theonlyanil** [comment]
In my case, only Pry-fi works, none of the rest worked. NONE.
But pry-fi has a disadvantage, we cannot change Mac address on our own.
