### ISSUE TITLE
Feature suggestion: Don't auto connect to some WiFi

### ISSUE THREAD

**Issue by ShapeShifter499** [BramBonne/privacypolice#50]
I'd like to see a feature where we can choose which WiFi access points we do not want to auto connect to. I currently connect sometimes to WiFi access points like ISP supported access points or Starbucks, etc. But I only want to connect when cell service is iffy or slower than what I'd expect from these free WiFi access points which I can't configure in Lineage OS 14.1 (Nougat 7.1).

**Comment by BramBonne** [comment]
That sounds like a great idea! However, I'm trying to keep the functionality of PrivacyPolice as security-oriented as possible.

This seems like a perfect idea for a new app. In case you want to develop something like this, feel free to use anything useful you can grab from the code of PrivacyPolice. All I ask is that you apply the GPL and give credit where due.

Kind regards,
Bram
