### ISSUE TITLE
Protection against KnownBeacons?

### ISSUE THREAD

**Issue by rugk** [BramBonne/privacypolice#52]
Does this app protect against the attack "Known WiFi beacons" presented at the 34c3? https://events.ccc.de/congress/2017/wiki/index.php/Lightning:Known_Beacons_Wi-Fi_Automatic_Association_Attack

The attack is supposed to be implemented in https://wifiphisher.org/.

**Comment by BramBonne** [comment]
From what I can gather from their documentation, PrivacyPolice _partially_ protects against their attack. When an alternative access point tries to spoof a network by using their SSID and security configuration only, PrivacyPolice can detect this and prevent your phone from connecting to the rogue network. *However*, if Wifiphisher also copies the MAC address from the legitimate access point (which it can do if the legitimate access point is also in range), then there is nothing PrivacyPolice can do.

Hope this answers your question.

Kind regards,
Bram
