### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by ale5000-git** [BramBonne/privacypolice#53]
Hi,
when is a new version release planned?

**Comment by BramBonne** [comment]
Thanks for asking!

I'm currently not actively developing Wi-Fi PrivacyPolice due to other work. However, I'm happy to take and check any pull requests sent my way, and incorporate them into a quick release!

Kind regards,
Bram

**Comment by ale5000-git** [comment]
Thanks for the reply, I was asking because there are already unreleased changes on GitHub.

**Comment by ale5000-git** [comment]
@BramBonne
Hi,
thanks for the reply.

I wasn't asking any new code change, could you please release a new version (with the **already committed** changes) when you have time?

**Comment by beerisgood** [comment]
*Push*
