### ISSUE TITLE
Protection against new networks dont work with LineageOS 15.1 (Android 8.1)

### ISSUE THREAD

**Issue by beerisgood** [BramBonne/privacypolice#56]
If i connect to a new network, i got the popup if i want allow it, but the connection isnt blocked.
Yes, i allow and enable GPS.

How can i verify that the other features still work?

**Comment by beerisgood** [comment]
*Push*

**Comment by beerisgood** [comment]
*last push try, else https://github.com/BramBonne/privacypolice/issues/57 *

**Comment by beerisgood** [comment]
I leave this here. See #57

**Comment by genodeftest** [comment]
Same here on an almost-stock (Nokia) Android 8 and 9.
