### ISSUE TITLE
Feature Request: Granular "Data protection" Management Capabilities

### ISSUE THREAD

**Issue by raulsiles** [BramBonne/privacypolice#6]
Hi Bram,
First of all, congrats for your Wi-Fi Privacy Police Android app!

I think it would be very interesting to add granular management capabilities for the access points (APs) registered by the "Data protection" feature. Instead of just having a single "Clear allowed and blocked hotspots" option, I would provide an advanced option (replacing the current one, or simply complementing it for advanced users) to be able to manage each trusted (or untrusted) entry individually.

The suggested new option should allow the user to get access (view) the current list of trusted/untrusted APs (including at least the network name (SSID) and all the associated MAC addresses (BSSIDs: 1-N)), and also provide edit capabilities, at least to be able to simply delete one of the entries individually (instead of them all, as it works currently). By entry I mean a single association between a SSID and a BSSID, as there can be multiple BSSIDs pointing to the same SSID.

This would allow users to have visibility on the current list of trusted/untrusted APs, and also allow them to clean it up easily, for example, when an single AP is replaced at home or at the office.

Cheers,
Raul

**Comment by BramBonne** [comment]
Hi Raul,

Thanks! I was already considering adding an 'individual hotspot editor' somewhere in the application, but was afraid that it would confuse some users. Adding it as an advanced option is a great idea! I'm adding this to my to-do list.

Best regards,
Bram

**Comment by benedetto** [comment]
Great point, I was about to open a similar request. My use case:

I work at a university where there are access points spread over the whole campus that use all the same SSID but of course different MAC addresses. I had to disable the "data protection" feature since every time I entered a new building or area, I was asked about that known network using a new MAC address. Therefore it would be nice to have at least something like a whitelist for certain networks which allows these networks to use more than one MAC address.

**Comment by BramBonne** [comment]
Hi all,

The latest git version now has an individual hotspot editor. I'm currently beta testing the functionality, and will release it in the following days.

@benedetto: I am currently not adding whitelisting functionality. My rationale is as follows:
* Whitelisting a single network would essentially negate the data protection functionality, as an attacker knowing the network it has to spoof to trick your device into connecting will know it has to try the network of your university. You could then just as easily disable this functionality, while still being protected against network leakage attacks.
* Adding whitelisting functionality will make the checking code slightly less simple, adding the chance of bugs in the core component of PrivacyPolice.
* The only situation I can think of where this *could* be a good idea is when using a WPA2-enterprise network where an attacker does not know your credentials. But in this case, just adding an option to automatically trust these networks seems more reasonable.

Please let me know if you have any good arguments for adding whitelist functionality (by opening a new issue), and I will consider adding it :-)

**Comment by benedetto** [comment]
@BramBonne No worries! I'm totally fine with allowing the 5 to 10 MAC adresses I meet at a regular basis in my university and it is actually my preferred solution as well. The whitelisting idea was more like a fallback solution for the case that you don't want to include such a fine-grained solution as the hotspot editor.

So thanks for the great work and I'm looking forward to the next version!

**Comment by Fiouz** [comment]
@BramBonne Can something similar to that be implemented for EAP enabled network configurations to address your 3rd point?
```
diff --git a/privacypolice/src/main/java/be/uhasselt/privacypolice/ScanResultsChecker.java b/privacypolice/src/main/java/be/uhasselt/privacypolice/ScanResultsChecker.java
index a840ae2..dc21444 100644
--- a/privacypolice/src/main/java/be/uhasselt/privacypolice/ScanResultsChecker.java
+++ b/privacypolice/src/main/java/be/uhasselt/privacypolice/ScanResultsChecker.java
@@ -19,12 +19,15 @@

 package be.uhasselt.privacypolice;

+import android.annotation.TargetApi;
 import android.content.BroadcastReceiver;
 import android.content.Context;
 import android.content.Intent;
 import android.net.wifi.ScanResult;
 import android.net.wifi.WifiConfiguration;
+import android.net.wifi.WifiEnterpriseConfig;
 import android.net.wifi.WifiManager;
+import android.os.Build;
 import android.util.Log;

 import java.util.List;
@@ -170,7 +173,31 @@ public class ScanResultsChecker extends BroadcastReceiver {
         // Strip double quotes (") from the SSID string
         String plainSSID = network.SSID.substring(1, network.SSID.length() - 1);

-        return getNetworkSafety(plainSSID, scanResults);
+        AccessPointSafety networkSafety = getNetworkSafety(plainSSID, scanResults);
+
+        // give a chance to reject UNTRUSTED AP
+        if (networkSafety == AccessPointSafety.UNKNOWN && prefs.getTrustEap() && isEapEnabled(network)) {
+            return AccessPointSafety.TRUSTED;
+        }
+
+        return networkSafety;
+    }
+
+    /**
+     * Checks whether the given network configuration is EAP enabled. Note that the checked field is
+     * only available in API 18 (JELLY_BEAN_MR2), hence the hardcoded negative response for older
+     * platforms.
+     *
+     * @param network The network that should be checked
+     * @return true if the given network is EAP enabled
+     * @see WifiConfiguration#enterpriseConfig
+     */
+    @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR2)
+    protected boolean isEapEnabled(final WifiConfiguration network) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
+            return network.enterpriseConfig != null && network.enterpriseConfig.getEapMethod() != WifiEnterpriseConfig.Eap.NONE;
+        }
+        return false;
     }

     /**
```

(note: configuration elements not included)

Or should it be combined with matching the ScanResult capabilities against `[WPA2-EAP-...]` and/or per SSID setting (vs global flag `prefs.getTrustEap()`) ?

**Comment by BramBonne** [comment]
Hi Fiouz,

Thanks for your comment and your work! I like the idea behind your solution, and I think it could be default (instead of a config setting) if some conditions are satisfied:

* The Wi-Fi network should report that it is, in fact, an EAP enabled network (as part of the scan result).
* The remembered network has a certificate set, which makes sure that a spoofed hotspot will not be able to trick the Android device into supplying the user's 802.1x credentials.

I very much appreciate your effort of getting your hands dirty in the code :-) Could you please open a new issue for this? This helps us separate this proposal from the parent issue.

**Comment by raulsiles** [comment]
Hi Bram,
May I suggest that although that EAP behaviour is established as the default one (under the two conditions you have mentioned; BTW, please, ensure the certificate already set and the one obtained both match ;-p) there is still a config setting in case users want to disable it?

Cheers,
Raul

**Comment by BramBonne** [comment]
Hi Raul,

Absolutely! Thanks for noting that :-) I was planning on having an 'advanced options' menu containing exactly that on an opt-out basis.
