### ISSUE TITLE
[NFR] Multi-user support

### ISSUE THREAD

**Issue by scento** [BramBonne/privacypolice#8]
As of today, this app blocks traffic from additional android users, which might not have installed the app. The rules should only apply to the current user, since this behavior causes network failures for all other users on the device.

**Comment by BramBonne** [comment]
Hi Wenzel, thanks for your suggestion!

I'm currently looking into how PrivacyPolice could support multiple users; receiving the ACTION_USER_BACKGROUND and ACTION_USER_FOREGROUND intents looks promising. I'm pasting them here as a future reference to myself:

http://developer.android.com/reference/android/content/Intent.html#ACTION_USER_BACKGROUND

**Comment by BramBonne** [comment]
Multi-user support was added in commit https://github.com/BramBonne/privacypolice/commit/ce22c837d178526a1e1aa13c1a193d3b778d2c16 and will be added in the next release.

**Comment by chepec** [comment]
Has this commit been released to Google's Play Store yet? I am running version 2.0 and had this exact problem on my tablet just now. Took a few minutes to figure out it was privacypolice, but kind of annoying since the only fix is to disable/uninstall the app.

**Comment by BramBonne** [comment]
Hi chepec, thanks for your comment.

I had to revert the multi-user functionality, since it was behaving unexpectedly on different Android devices. Apparently, multi-user support for applications is only consistent for system-level apps. If anyone knows of a way in which this could be implemented, I'd be happy to be proven wrong (I also welcome patches!).

In meantime, you can fix this by also installing Wi-Fi PrivacyPolice for the second user, in which case this instance will take over.

**Comment by chepec** [comment]
Thanks for the suggested work-around. But there's something finicky going on.
I made sure to install on primary account first, disabled both "privacy protection" and "data protection", and then installed the app on the second account, similarly disabled. Went back to the primary account, enabled everything, added Wifi to "known hotspots", and then did the same on the second account.

The weird part is that the wifi connection is now disabled on the primary account, and constantly (every ~20 seconds) drops and reconnects on the second account. Clearly, not workable :-)
Can you confirm that multi-user install works? And should one follow any particular install procedure (is there perhaps a way to install to all users in one step)?

This is on Android 4.4.4 (CM11-20141115-snapshot-M12-flo) on a Nexus 7.

**Comment by BramBonne** [comment]
Thanks for your extensive testing (and sorry for my late reply)! I have not tested this as much as you did, so I'm afraid that what I thought was a complete workaround does not work all too well in real-world situations.

At this point, I'm not sure there's anything I can do: I seem to have tried out all options for multi-user support on Android, but it looks like none of them is sufficient when listening for system-level broadcasts. Again, if you know of any other options, I'll happily implement them (or accept patches). In meantime, it seems that multi-user support is definitely a YMMV-situation.
